//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace XJDAO
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class XJ_Entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“XJ_Entities”部分中的连接字符串初始化新 XJ_Entities 对象。
        /// </summary>
        public XJ_Entities() : base("name=XJ_Entities", "XJ_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 XJ_Entities 对象。
        /// </summary>
        public XJ_Entities(string connectionString) : base(connectionString, "XJ_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 XJ_Entities 对象。
        /// </summary>
        public XJ_Entities(EntityConnection connection) : base(connection, "XJ_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_BUILDING> B_BUILDING
        {
            get
            {
                if ((_B_BUILDING == null))
                {
                    _B_BUILDING = base.CreateObjectSet<B_BUILDING>("B_BUILDING");
                }
                return _B_BUILDING;
            }
        }
        private ObjectSet<B_BUILDING> _B_BUILDING;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_BUILDING_UNIT> B_BUILDING_UNIT
        {
            get
            {
                if ((_B_BUILDING_UNIT == null))
                {
                    _B_BUILDING_UNIT = base.CreateObjectSet<B_BUILDING_UNIT>("B_BUILDING_UNIT");
                }
                return _B_BUILDING_UNIT;
            }
        }
        private ObjectSet<B_BUILDING_UNIT> _B_BUILDING_UNIT;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_CITIES> B_CITIES
        {
            get
            {
                if ((_B_CITIES == null))
                {
                    _B_CITIES = base.CreateObjectSet<B_CITIES>("B_CITIES");
                }
                return _B_CITIES;
            }
        }
        private ObjectSet<B_CITIES> _B_CITIES;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_MONITOR> B_MONITOR
        {
            get
            {
                if ((_B_MONITOR == null))
                {
                    _B_MONITOR = base.CreateObjectSet<B_MONITOR>("B_MONITOR");
                }
                return _B_MONITOR;
            }
        }
        private ObjectSet<B_MONITOR> _B_MONITOR;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_POINT> B_POINT
        {
            get
            {
                if ((_B_POINT == null))
                {
                    _B_POINT = base.CreateObjectSet<B_POINT>("B_POINT");
                }
                return _B_POINT;
            }
        }
        private ObjectSet<B_POINT> _B_POINT;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_PROJECT> B_PROJECT
        {
            get
            {
                if ((_B_PROJECT == null))
                {
                    _B_PROJECT = base.CreateObjectSet<B_PROJECT>("B_PROJECT");
                }
                return _B_PROJECT;
            }
        }
        private ObjectSet<B_PROJECT> _B_PROJECT;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_PROVINCES> B_PROVINCES
        {
            get
            {
                if ((_B_PROVINCES == null))
                {
                    _B_PROVINCES = base.CreateObjectSet<B_PROVINCES>("B_PROVINCES");
                }
                return _B_PROVINCES;
            }
        }
        private ObjectSet<B_PROVINCES> _B_PROVINCES;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<B_UPPER_MONITOR> B_UPPER_MONITOR
        {
            get
            {
                if ((_B_UPPER_MONITOR == null))
                {
                    _B_UPPER_MONITOR = base.CreateObjectSet<B_UPPER_MONITOR>("B_UPPER_MONITOR");
                }
                return _B_UPPER_MONITOR;
            }
        }
        private ObjectSet<B_UPPER_MONITOR> _B_UPPER_MONITOR;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<P_PointData> P_PointData
        {
            get
            {
                if ((_P_PointData == null))
                {
                    _P_PointData = base.CreateObjectSet<P_PointData>("P_PointData");
                }
                return _P_PointData;
            }
        }
        private ObjectSet<P_PointData> _P_PointData;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 B_BUILDING EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_BUILDING(B_BUILDING b_BUILDING)
        {
            base.AddObject("B_BUILDING", b_BUILDING);
        }
    
        /// <summary>
        /// 用于向 B_BUILDING_UNIT EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_BUILDING_UNIT(B_BUILDING_UNIT b_BUILDING_UNIT)
        {
            base.AddObject("B_BUILDING_UNIT", b_BUILDING_UNIT);
        }
    
        /// <summary>
        /// 用于向 B_CITIES EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_CITIES(B_CITIES b_CITIES)
        {
            base.AddObject("B_CITIES", b_CITIES);
        }
    
        /// <summary>
        /// 用于向 B_MONITOR EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_MONITOR(B_MONITOR b_MONITOR)
        {
            base.AddObject("B_MONITOR", b_MONITOR);
        }
    
        /// <summary>
        /// 用于向 B_POINT EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_POINT(B_POINT b_POINT)
        {
            base.AddObject("B_POINT", b_POINT);
        }
    
        /// <summary>
        /// 用于向 B_PROJECT EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_PROJECT(B_PROJECT b_PROJECT)
        {
            base.AddObject("B_PROJECT", b_PROJECT);
        }
    
        /// <summary>
        /// 用于向 B_PROVINCES EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_PROVINCES(B_PROVINCES b_PROVINCES)
        {
            base.AddObject("B_PROVINCES", b_PROVINCES);
        }
    
        /// <summary>
        /// 用于向 B_UPPER_MONITOR EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToB_UPPER_MONITOR(B_UPPER_MONITOR b_UPPER_MONITOR)
        {
            base.AddObject("B_UPPER_MONITOR", b_UPPER_MONITOR);
        }
    
        /// <summary>
        /// 用于向 P_PointData EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToP_PointData(P_PointData p_PointData)
        {
            base.AddObject("P_PointData", p_PointData);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_BUILDING")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_BUILDING : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_BUILDING 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static B_BUILDING CreateB_BUILDING(global::System.Int32 id)
        {
            B_BUILDING b_BUILDING = new B_BUILDING();
            b_BUILDING.id = id;
            return b_BUILDING;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String building_code
        {
            get
            {
                return _building_code;
            }
            set
            {
                Onbuilding_codeChanging(value);
                ReportPropertyChanging("building_code");
                _building_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("building_code");
                Onbuilding_codeChanged();
            }
        }
        private global::System.String _building_code;
        partial void Onbuilding_codeChanging(global::System.String value);
        partial void Onbuilding_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String building_name
        {
            get
            {
                return _building_name;
            }
            set
            {
                Onbuilding_nameChanging(value);
                ReportPropertyChanging("building_name");
                _building_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("building_name");
                Onbuilding_nameChanged();
            }
        }
        private global::System.String _building_name;
        partial void Onbuilding_nameChanging(global::System.String value);
        partial void Onbuilding_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project_code
        {
            get
            {
                return _project_code;
            }
            set
            {
                Onproject_codeChanging(value);
                ReportPropertyChanging("project_code");
                _project_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project_code");
                Onproject_codeChanged();
            }
        }
        private global::System.String _project_code;
        partial void Onproject_codeChanging(global::System.String value);
        partial void Onproject_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private Nullable<global::System.Int32> _type;
        partial void OntypeChanging(Nullable<global::System.Int32> value);
        partial void OntypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                Oncreate_dateChanging(value);
                ReportPropertyChanging("create_date");
                _create_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_date");
                Oncreate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _create_date;
        partial void Oncreate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreate_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_BUILDING_UNIT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_BUILDING_UNIT : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_BUILDING_UNIT 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static B_BUILDING_UNIT CreateB_BUILDING_UNIT(global::System.Int32 id)
        {
            B_BUILDING_UNIT b_BUILDING_UNIT = new B_BUILDING_UNIT();
            b_BUILDING_UNIT.id = id;
            return b_BUILDING_UNIT;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String unit_name
        {
            get
            {
                return _unit_name;
            }
            set
            {
                Onunit_nameChanging(value);
                ReportPropertyChanging("unit_name");
                _unit_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("unit_name");
                Onunit_nameChanged();
            }
        }
        private global::System.String _unit_name;
        partial void Onunit_nameChanging(global::System.String value);
        partial void Onunit_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String building_code
        {
            get
            {
                return _building_code;
            }
            set
            {
                Onbuilding_codeChanging(value);
                ReportPropertyChanging("building_code");
                _building_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("building_code");
                Onbuilding_codeChanged();
            }
        }
        private global::System.String _building_code;
        partial void Onbuilding_codeChanging(global::System.String value);
        partial void Onbuilding_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                Oncreate_dateChanging(value);
                ReportPropertyChanging("create_date");
                _create_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_date");
                Oncreate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _create_date;
        partial void Oncreate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreate_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_CITIES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_CITIES : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_CITIES 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="cityid">cityid 属性的初始值。</param>
        /// <param name="city">city 属性的初始值。</param>
        /// <param name="provinceid">provinceid 属性的初始值。</param>
        public static B_CITIES CreateB_CITIES(global::System.Int32 id, global::System.String cityid, global::System.String city, global::System.String provinceid)
        {
            B_CITIES b_CITIES = new B_CITIES();
            b_CITIES.id = id;
            b_CITIES.cityid = cityid;
            b_CITIES.city = city;
            b_CITIES.provinceid = provinceid;
            return b_CITIES;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cityid
        {
            get
            {
                return _cityid;
            }
            set
            {
                OncityidChanging(value);
                ReportPropertyChanging("cityid");
                _cityid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cityid");
                OncityidChanged();
            }
        }
        private global::System.String _cityid;
        partial void OncityidChanging(global::System.String value);
        partial void OncityidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String provinceid
        {
            get
            {
                return _provinceid;
            }
            set
            {
                OnprovinceidChanging(value);
                ReportPropertyChanging("provinceid");
                _provinceid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("provinceid");
                OnprovinceidChanged();
            }
        }
        private global::System.String _provinceid;
        partial void OnprovinceidChanging(global::System.String value);
        partial void OnprovinceidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_MONITOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_MONITOR : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_MONITOR 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static B_MONITOR CreateB_MONITOR(global::System.Int32 id)
        {
            B_MONITOR b_MONITOR = new B_MONITOR();
            b_MONITOR.id = id;
            return b_MONITOR;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String monitor_code
        {
            get
            {
                return _monitor_code;
            }
            set
            {
                Onmonitor_codeChanging(value);
                ReportPropertyChanging("monitor_code");
                _monitor_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("monitor_code");
                Onmonitor_codeChanged();
            }
        }
        private global::System.String _monitor_code;
        partial void Onmonitor_codeChanging(global::System.String value);
        partial void Onmonitor_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String monitor_name
        {
            get
            {
                return _monitor_name;
            }
            set
            {
                Onmonitor_nameChanging(value);
                ReportPropertyChanging("monitor_name");
                _monitor_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("monitor_name");
                Onmonitor_nameChanged();
            }
        }
        private global::System.String _monitor_name;
        partial void Onmonitor_nameChanging(global::System.String value);
        partial void Onmonitor_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project_code
        {
            get
            {
                return _project_code;
            }
            set
            {
                Onproject_codeChanging(value);
                ReportPropertyChanging("project_code");
                _project_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project_code");
                Onproject_codeChanged();
            }
        }
        private global::System.String _project_code;
        partial void Onproject_codeChanging(global::System.String value);
        partial void Onproject_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String upper_code
        {
            get
            {
                return _upper_code;
            }
            set
            {
                Onupper_codeChanging(value);
                ReportPropertyChanging("upper_code");
                _upper_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upper_code");
                Onupper_codeChanged();
            }
        }
        private global::System.String _upper_code;
        partial void Onupper_codeChanging(global::System.String value);
        partial void Onupper_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String port_name
        {
            get
            {
                return _port_name;
            }
            set
            {
                Onport_nameChanging(value);
                ReportPropertyChanging("port_name");
                _port_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("port_name");
                Onport_nameChanged();
            }
        }
        private global::System.String _port_name;
        partial void Onport_nameChanging(global::System.String value);
        partial void Onport_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> baud_rate
        {
            get
            {
                return _baud_rate;
            }
            set
            {
                Onbaud_rateChanging(value);
                ReportPropertyChanging("baud_rate");
                _baud_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("baud_rate");
                Onbaud_rateChanged();
            }
        }
        private Nullable<global::System.Int32> _baud_rate;
        partial void Onbaud_rateChanging(Nullable<global::System.Int32> value);
        partial void Onbaud_rateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> stop_bit
        {
            get
            {
                return _stop_bit;
            }
            set
            {
                Onstop_bitChanging(value);
                ReportPropertyChanging("stop_bit");
                _stop_bit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stop_bit");
                Onstop_bitChanged();
            }
        }
        private Nullable<global::System.Int32> _stop_bit;
        partial void Onstop_bitChanging(Nullable<global::System.Int32> value);
        partial void Onstop_bitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parity_check
        {
            get
            {
                return _parity_check;
            }
            set
            {
                Onparity_checkChanging(value);
                ReportPropertyChanging("parity_check");
                _parity_check = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parity_check");
                Onparity_checkChanged();
            }
        }
        private Nullable<global::System.Int32> _parity_check;
        partial void Onparity_checkChanging(Nullable<global::System.Int32> value);
        partial void Onparity_checkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> channel_count
        {
            get
            {
                return _channel_count;
            }
            set
            {
                Onchannel_countChanging(value);
                ReportPropertyChanging("channel_count");
                _channel_count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("channel_count");
                Onchannel_countChanged();
            }
        }
        private Nullable<global::System.Int32> _channel_count;
        partial void Onchannel_countChanging(Nullable<global::System.Int32> value);
        partial void Onchannel_countChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                Oncreate_dateChanging(value);
                ReportPropertyChanging("create_date");
                _create_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_date");
                Oncreate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _create_date;
        partial void Oncreate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreate_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_POINT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_POINT : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_POINT 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static B_POINT CreateB_POINT(global::System.Int32 id)
        {
            B_POINT b_POINT = new B_POINT();
            b_POINT.id = id;
            return b_POINT;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String point_name
        {
            get
            {
                return _point_name;
            }
            set
            {
                Onpoint_nameChanging(value);
                ReportPropertyChanging("point_name");
                _point_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("point_name");
                Onpoint_nameChanged();
            }
        }
        private global::System.String _point_name;
        partial void Onpoint_nameChanging(global::System.String value);
        partial void Onpoint_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String monitor_code
        {
            get
            {
                return _monitor_code;
            }
            set
            {
                Onmonitor_codeChanging(value);
                ReportPropertyChanging("monitor_code");
                _monitor_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("monitor_code");
                Onmonitor_codeChanged();
            }
        }
        private global::System.String _monitor_code;
        partial void Onmonitor_codeChanging(global::System.String value);
        partial void Onmonitor_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> channel_idx
        {
            get
            {
                return _channel_idx;
            }
            set
            {
                Onchannel_idxChanging(value);
                ReportPropertyChanging("channel_idx");
                _channel_idx = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("channel_idx");
                Onchannel_idxChanged();
            }
        }
        private Nullable<global::System.Int32> _channel_idx;
        partial void Onchannel_idxChanging(Nullable<global::System.Int32> value);
        partial void Onchannel_idxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> unit_id
        {
            get
            {
                return _unit_id;
            }
            set
            {
                Onunit_idChanging(value);
                ReportPropertyChanging("unit_id");
                _unit_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unit_id");
                Onunit_idChanged();
            }
        }
        private Nullable<global::System.Int32> _unit_id;
        partial void Onunit_idChanging(Nullable<global::System.Int32> value);
        partial void Onunit_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String group_name
        {
            get
            {
                return _group_name;
            }
            set
            {
                Ongroup_nameChanging(value);
                ReportPropertyChanging("group_name");
                _group_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("group_name");
                Ongroup_nameChanged();
            }
        }
        private global::System.String _group_name;
        partial void Ongroup_nameChanging(global::System.String value);
        partial void Ongroup_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> signal_type
        {
            get
            {
                return _signal_type;
            }
            set
            {
                Onsignal_typeChanging(value);
                ReportPropertyChanging("signal_type");
                _signal_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("signal_type");
                Onsignal_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _signal_type;
        partial void Onsignal_typeChanging(Nullable<global::System.Int32> value);
        partial void Onsignal_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> lower_limit
        {
            get
            {
                return _lower_limit;
            }
            set
            {
                Onlower_limitChanging(value);
                ReportPropertyChanging("lower_limit");
                _lower_limit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lower_limit");
                Onlower_limitChanged();
            }
        }
        private Nullable<global::System.Decimal> _lower_limit;
        partial void Onlower_limitChanging(Nullable<global::System.Decimal> value);
        partial void Onlower_limitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> upper_limit
        {
            get
            {
                return _upper_limit;
            }
            set
            {
                Onupper_limitChanging(value);
                ReportPropertyChanging("upper_limit");
                _upper_limit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("upper_limit");
                Onupper_limitChanged();
            }
        }
        private Nullable<global::System.Decimal> _upper_limit;
        partial void Onupper_limitChanging(Nullable<global::System.Decimal> value);
        partial void Onupper_limitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private Nullable<global::System.Int32> _state;
        partial void OnstateChanging(Nullable<global::System.Int32> value);
        partial void OnstateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                Oncreate_dateChanging(value);
                ReportPropertyChanging("create_date");
                _create_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_date");
                Oncreate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _create_date;
        partial void Oncreate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreate_dateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_PROJECT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_PROJECT : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_PROJECT 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static B_PROJECT CreateB_PROJECT(global::System.Int32 id)
        {
            B_PROJECT b_PROJECT = new B_PROJECT();
            b_PROJECT.id = id;
            return b_PROJECT;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project_code
        {
            get
            {
                return _project_code;
            }
            set
            {
                Onproject_codeChanging(value);
                ReportPropertyChanging("project_code");
                _project_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project_code");
                Onproject_codeChanged();
            }
        }
        private global::System.String _project_code;
        partial void Onproject_codeChanging(global::System.String value);
        partial void Onproject_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project_name
        {
            get
            {
                return _project_name;
            }
            set
            {
                Onproject_nameChanging(value);
                ReportPropertyChanging("project_name");
                _project_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project_name");
                Onproject_nameChanged();
            }
        }
        private global::System.String _project_name;
        partial void Onproject_nameChanging(global::System.String value);
        partial void Onproject_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String province
        {
            get
            {
                return _province;
            }
            set
            {
                OnprovinceChanging(value);
                ReportPropertyChanging("province");
                _province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("province");
                OnprovinceChanged();
            }
        }
        private global::System.String _province;
        partial void OnprovinceChanging(global::System.String value);
        partial void OnprovinceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pm
        {
            get
            {
                return _pm;
            }
            set
            {
                OnpmChanging(value);
                ReportPropertyChanging("pm");
                _pm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pm");
                OnpmChanged();
            }
        }
        private global::System.String _pm;
        partial void OnpmChanging(global::System.String value);
        partial void OnpmChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone_no
        {
            get
            {
                return _phone_no;
            }
            set
            {
                Onphone_noChanging(value);
                ReportPropertyChanging("phone_no");
                _phone_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone_no");
                Onphone_noChanged();
            }
        }
        private global::System.String _phone_no;
        partial void Onphone_noChanging(global::System.String value);
        partial void Onphone_noChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                Oncreate_dateChanging(value);
                ReportPropertyChanging("create_date");
                _create_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_date");
                Oncreate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _create_date;
        partial void Oncreate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreate_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_PROVINCES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_PROVINCES : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_PROVINCES 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="provinceid">provinceid 属性的初始值。</param>
        /// <param name="province">province 属性的初始值。</param>
        public static B_PROVINCES CreateB_PROVINCES(global::System.Int32 id, global::System.String provinceid, global::System.String province)
        {
            B_PROVINCES b_PROVINCES = new B_PROVINCES();
            b_PROVINCES.id = id;
            b_PROVINCES.provinceid = provinceid;
            b_PROVINCES.province = province;
            return b_PROVINCES;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String provinceid
        {
            get
            {
                return _provinceid;
            }
            set
            {
                OnprovinceidChanging(value);
                ReportPropertyChanging("provinceid");
                _provinceid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("provinceid");
                OnprovinceidChanged();
            }
        }
        private global::System.String _provinceid;
        partial void OnprovinceidChanging(global::System.String value);
        partial void OnprovinceidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String province
        {
            get
            {
                return _province;
            }
            set
            {
                OnprovinceChanging(value);
                ReportPropertyChanging("province");
                _province = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("province");
                OnprovinceChanged();
            }
        }
        private global::System.String _province;
        partial void OnprovinceChanging(global::System.String value);
        partial void OnprovinceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="B_UPPER_MONITOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class B_UPPER_MONITOR : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 B_UPPER_MONITOR 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static B_UPPER_MONITOR CreateB_UPPER_MONITOR(global::System.Int32 id)
        {
            B_UPPER_MONITOR b_UPPER_MONITOR = new B_UPPER_MONITOR();
            b_UPPER_MONITOR.id = id;
            return b_UPPER_MONITOR;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String upper_code
        {
            get
            {
                return _upper_code;
            }
            set
            {
                Onupper_codeChanging(value);
                ReportPropertyChanging("upper_code");
                _upper_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upper_code");
                Onupper_codeChanged();
            }
        }
        private global::System.String _upper_code;
        partial void Onupper_codeChanging(global::System.String value);
        partial void Onupper_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String upper_name
        {
            get
            {
                return _upper_name;
            }
            set
            {
                Onupper_nameChanging(value);
                ReportPropertyChanging("upper_name");
                _upper_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upper_name");
                Onupper_nameChanged();
            }
        }
        private global::System.String _upper_name;
        partial void Onupper_nameChanging(global::System.String value);
        partial void Onupper_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project_code
        {
            get
            {
                return _project_code;
            }
            set
            {
                Onproject_codeChanging(value);
                ReportPropertyChanging("project_code");
                _project_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project_code");
                Onproject_codeChanged();
            }
        }
        private global::System.String _project_code;
        partial void Onproject_codeChanging(global::System.String value);
        partial void Onproject_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private Nullable<global::System.Int32> _state;
        partial void OnstateChanging(Nullable<global::System.Int32> value);
        partial void OnstateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                Oncreate_dateChanging(value);
                ReportPropertyChanging("create_date");
                _create_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_date");
                Oncreate_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _create_date;
        partial void Oncreate_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreate_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XJ_Model", Name="P_PointData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class P_PointData : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 P_PointData 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static P_PointData CreateP_PointData(global::System.Int64 id)
        {
            P_PointData p_PointData = new P_PointData();
            p_PointData.id = id;
            return p_PointData;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String project_code
        {
            get
            {
                return _project_code;
            }
            set
            {
                Onproject_codeChanging(value);
                ReportPropertyChanging("project_code");
                _project_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("project_code");
                Onproject_codeChanged();
            }
        }
        private global::System.String _project_code;
        partial void Onproject_codeChanging(global::System.String value);
        partial void Onproject_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String building_code
        {
            get
            {
                return _building_code;
            }
            set
            {
                Onbuilding_codeChanging(value);
                ReportPropertyChanging("building_code");
                _building_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("building_code");
                Onbuilding_codeChanged();
            }
        }
        private global::System.String _building_code;
        partial void Onbuilding_codeChanging(global::System.String value);
        partial void Onbuilding_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> unit_id
        {
            get
            {
                return _unit_id;
            }
            set
            {
                Onunit_idChanging(value);
                ReportPropertyChanging("unit_id");
                _unit_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("unit_id");
                Onunit_idChanged();
            }
        }
        private Nullable<global::System.Int32> _unit_id;
        partial void Onunit_idChanging(Nullable<global::System.Int32> value);
        partial void Onunit_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String upper_code
        {
            get
            {
                return _upper_code;
            }
            set
            {
                Onupper_codeChanging(value);
                ReportPropertyChanging("upper_code");
                _upper_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upper_code");
                Onupper_codeChanged();
            }
        }
        private global::System.String _upper_code;
        partial void Onupper_codeChanging(global::System.String value);
        partial void Onupper_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String monitor_code
        {
            get
            {
                return _monitor_code;
            }
            set
            {
                Onmonitor_codeChanging(value);
                ReportPropertyChanging("monitor_code");
                _monitor_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("monitor_code");
                Onmonitor_codeChanged();
            }
        }
        private global::System.String _monitor_code;
        partial void Onmonitor_codeChanging(global::System.String value);
        partial void Onmonitor_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> point_id
        {
            get
            {
                return _point_id;
            }
            set
            {
                Onpoint_idChanging(value);
                ReportPropertyChanging("point_id");
                _point_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("point_id");
                Onpoint_idChanged();
            }
        }
        private Nullable<global::System.Int32> _point_id;
        partial void Onpoint_idChanging(Nullable<global::System.Int32> value);
        partial void Onpoint_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> val
        {
            get
            {
                return _val;
            }
            set
            {
                OnvalChanging(value);
                ReportPropertyChanging("val");
                _val = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("val");
                OnvalChanged();
            }
        }
        private Nullable<global::System.Decimal> _val;
        partial void OnvalChanging(Nullable<global::System.Decimal> value);
        partial void OnvalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> input_time
        {
            get
            {
                return _input_time;
            }
            set
            {
                Oninput_timeChanging(value);
                ReportPropertyChanging("input_time");
                _input_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("input_time");
                Oninput_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _input_time;
        partial void Oninput_timeChanging(Nullable<global::System.DateTime> value);
        partial void Oninput_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String group_name
        {
            get
            {
                return _group_name;
            }
            set
            {
                Ongroup_nameChanging(value);
                ReportPropertyChanging("group_name");
                _group_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("group_name");
                Ongroup_nameChanged();
            }
        }
        private global::System.String _group_name;
        partial void Ongroup_nameChanging(global::System.String value);
        partial void Ongroup_nameChanged();

        #endregion

    
    }

    #endregion

    
}
